### ISSUE TITLE
Error when checking if directory is empty

### ISSUE THREAD

**Issue by CotterpinDoozer** [CancerRegistryOfNorway/NORDCAN#28]
Line 112 to 118 in the script - the function that is checking whether the directory is empty - might not be functioning properly. 
I have tried both not having the folder there at all prior to running this, having an empty folder and having a folder with files, and I always get the same result: the script gives feedback that the directory is not empty. 

Can you test it and see if you get another result? Test it in sensitive sone, on P:\dataflyt.... so we have the same environment.

**Comment by HuidongTian** [comment]
@CotterpinDoozer That piece of script checks both directories "dir_result" and "dir_archive", any of these folders is not empty will trigger the stop warning message. I tested by creating two empty folders, it works as expected. Maybe you forget the "dir_archive"?

**Comment by CotterpinDoozer** [comment]
Yes, that might be. I will test it next time! I will set the task to myself.

**Comment by AnnaSkog** [comment]
I just tested this quickly because I was using nordcan.R. 

I set an empty folder for the results in line 79 (dir_result). But the line 87-100 makes the following two folders in my results directory: “iarctools” and “survival”. So then, when I run line 112-118 I get at error notice because the dir_result are no longer empty. 

I can show you if you want to.

**Comment by HuidongTian** [comment]
Fixed. 

https://github.com/CancerRegistryOfNorway/NORDCAN/blob/master/nordcan_participant_instructions/nordcan.R#L113

**Comment by AnnaSkog** [comment]
I tested the updated version of nordcan.R and it seems to be working as expected now.
